name: 🐍 GitHub Contribution Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      # 🔥 STEP 1: Generate "food" (commits)
      - name: 🍔 Generate Contribution Food
        run: |
          git config --global user.name "vishalyadav0987"
          git config --global user.email "you@example.com"

          for i in {1..10}
          do
            git commit --allow-empty -m "🍔 food commit $i"
          done

          git push

      # 🐍 STEP 2: Generate Snake
      - name: 🐍 Generate Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 🚀 STEP 3: Deploy
      - name: 🚀 Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
